#!/bin/bash

ibmcloud iam service-id-create futurenoobK8s-default-id 

ibmcloud iam service-policy-create futurenoobK8s-default-id  --roles Reader  --service-name container-registry

ibmcloud iam service-api-key-create futurenoobK8s-default-key futurenoobK8s-default-id

kubectl --namespace default create secret docker-registry imagepullsecret --docker-server=de.icr.io --docker-username=iamapikey --docker-password=z_kJ_qr-28o3BTr5n1TCsC8CHt6kJj54SxrFpDmBYFiA --docker-email=riya@futurenoob.io

kubectl get secret

kubectl describe serviceaccount default

kubectl patch -n default serviceaccount/default -p '{"imagePullSecrets":[{"name": "imagepullsecret"}]}'

